# Generated by Django 3.1.4 on 2020-12-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvgen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemas',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='schemas',
            name='Company_name',
        ),
        migrations.RemoveField(
            model_name='schemas',
            name='Date_field',
        ),
        migrations.RemoveField(
            model_name='schemas',
            name='Domain_name',
        ),
        migrations.RemoveField(
            model_name='schemas',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='schemas',
            name='Full_name',
        ),
        migrations.RemoveField(
            model_name='schemas',
            name='Integer',
        ),
        migrations.RemoveField(
            model_name='schemas',
            name='Integer_range_from',
        ),
        migrations.RemoveField(
            model_name='schemas',
            name='Integer_range_to',
        ),
        migrations.RemoveField(
            model_name='schemas',
            name='Job',
        ),
        migrations.RemoveField(
            model_name='schemas',
            name='Phone_number',
        ),
        migrations.RemoveField(
            model_name='schemas',
            name='Text',
        ),
        migrations.RemoveField(
            model_name='schemas',
            name='Text_number',
        ),
        migrations.AddField(
            model_name='schemas',
            name='fields',
            field=models.TextField(default='[()]'),
        ),
    ]
