# Generated by Django 3.1.4 on 2020-12-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvgen', '0005_auto_20201215_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvfile',
            name='schema',
        ),
        migrations.AddField(
            model_name='csvfile',
            name='schema_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
