# Generated by Django 3.1.4 on 2020-12-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvgen', '0006_auto_20201215_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='is_ready',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
